spring.application.name=service-registry
server.port=8761
#spring.profiles.active=dev

## Tam vo hieu hoa cac noi dung cau hinh va su dung cau hinh tren cloud tu manage_config
spring.main.banner-mode=off

## Cau hinh Eureka Cloud
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

## Cau hinh ket noi voi service may chu quan ly cau hinh manage_config tai PORT 9999
## Tuy chon "optional" cho phep Spring ap dung cau hinh tai local khi noi dung cau hinh tren cloud khong hoat dong
## "configserver" la tu khoa mac dinh cua spring su dung de lay cau hinh tu may chu quan ly cau hinh
spring.config.import=optional:configserver:http://localhost:9999