spring.application.name=service-mvc
server.port=8989

# Tat logo Spring Boot khi khoi dong ung dung
spring.main.banner-mode=off

## id cua authentication service cap
auth-service-Id=xxx

## Cau hinh Eureka cho service client
eureka.client.service-url-defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## Cau hinh Zipkin
management.tracingsamplingprobability=1.0

## Cau hinh ket noi voi service may chu quan ly cau hinh manage_config
spring.config.import=optional:configserver:http://localhost:9999