spring.application.name=manage-config

server.port=9999
spring.main.banner-mode=off


## Cau hinh Eureka cho service client
eureka.client.service-url-defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## Cau hinh Zipkin
management.tracingsamplingprobability=1.0

## Cau hinh Spring Config cho manage_config service voi vai tro la may chu quan ly cau hinh
## Ket noi github voi service may chu manage_config
spring.cloud.config.server.git.uri=https://github.com/Quangdai2207/Spring-config
