POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
X-Client-Id: xxx

{
  "email" : "email@example.com",
  "password": "secretpassword",
  "confirmPassword": "secretpassword"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
X-Client-Id: bbc711da-5aee-43bd-b3a4-1781b76f7bfc

{
"email" : "daitran.inbox@gmail.com",
"password": "Admin@123"
}